Summary:   Package created with checkinstall 1.6.2
Name:      libiconv
Version:   1.13
Release:   shopex
License: GPL
Packager:  checkinstall-1.6.2
Group:     Applications/System          
BuildRoot: /var/tmp/tmp.gkCCY28051/package
Provides:  libiconv
Requires:  ,/bin/sh

%description
Package created with checkinstall 1.6.2

%files
%dir "//usr/"
%dir "//usr/include/"
"//usr/include/iconv.h"
"//usr/include/libcharset.h"
"//usr/include/localcharset.h"
%dir "//usr/lib/"
"//usr/lib/libcharset.so.1.0.0"
"//usr/lib/preloadable_libiconv.so"
"//usr/lib/libcharset.a"
"//usr/lib/charset.alias"
%dir "//usr/lib/libcharset.so"
%dir "//usr/lib/libiconv.so"
"//usr/lib/libiconv.la"
"//usr/lib/libiconv.so.2.5.0"
%dir "//usr/lib/libcharset.so.1"
"//usr/lib/libcharset.la"
%dir "//usr/lib/libiconv.so.2"
%dir "//usr/doc/"
%dir "//usr/doc/libiconv/"
"//usr/doc/libiconv/README.woe32"
"//usr/doc/libiconv/AUTHORS"
"//usr/doc/libiconv/COPYING.LIB"
"//usr/doc/libiconv/README.djgpp"
"//usr/doc/libiconv/COPYING"
"//usr/doc/libiconv/HACKING"
"//usr/doc/libiconv/ChangeLog"
%dir "//usr/doc/libiconv/doc/"
"//usr/doc/libiconv/doc/relocatable.texi"
"//usr/doc/libiconv/ABOUT-NLS"
"//usr/doc/libiconv/README"
"//usr/doc/libiconv/INSTALL.generic"
"//usr/doc/libiconv/NEWS"
"//usr/doc/libiconv/THANKS"
%dir "//usr/bin/"
"//usr/bin/iconv"
%dir "//usr/share/"
%dir "//usr/share/doc/"
%dir "//usr/share/doc/libiconv/"
"//usr/share/doc/libiconv/iconv.3.html"
"//usr/share/doc/libiconv/iconv.1.html"
"//usr/share/doc/libiconv/iconv_close.3.html"
"//usr/share/doc/libiconv/iconvctl.3.html"
"//usr/share/doc/libiconv/iconv_open_into.3.html"
"//usr/share/doc/libiconv/iconv_open.3.html"
%dir "//usr/share/locale/"
%dir "//usr/share/locale/gl/"
%dir "//usr/share/locale/gl/LC_MESSAGES/"
"//usr/share/locale/gl/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/ru/"
%dir "//usr/share/locale/ru/LC_MESSAGES/"
"//usr/share/locale/ru/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/pt_BR/"
%dir "//usr/share/locale/pt_BR/LC_MESSAGES/"
"//usr/share/locale/pt_BR/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/it/"
%dir "//usr/share/locale/it/LC_MESSAGES/"
"//usr/share/locale/it/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/zh_TW/"
%dir "//usr/share/locale/zh_TW/LC_MESSAGES/"
"//usr/share/locale/zh_TW/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/eo/"
%dir "//usr/share/locale/eo/LC_MESSAGES/"
"//usr/share/locale/eo/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/ca/"
%dir "//usr/share/locale/ca/LC_MESSAGES/"
"//usr/share/locale/ca/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/vi/"
%dir "//usr/share/locale/vi/LC_MESSAGES/"
"//usr/share/locale/vi/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/rm/"
%dir "//usr/share/locale/rm/LC_MESSAGES/"
"//usr/share/locale/rm/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/nl/"
%dir "//usr/share/locale/nl/LC_MESSAGES/"
"//usr/share/locale/nl/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/id/"
%dir "//usr/share/locale/id/LC_MESSAGES/"
"//usr/share/locale/id/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/es/"
%dir "//usr/share/locale/es/LC_MESSAGES/"
"//usr/share/locale/es/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/zh_CN/"
%dir "//usr/share/locale/zh_CN/LC_MESSAGES/"
"//usr/share/locale/zh_CN/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/et/"
%dir "//usr/share/locale/et/LC_MESSAGES/"
"//usr/share/locale/et/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/sr/"
%dir "//usr/share/locale/sr/LC_MESSAGES/"
"//usr/share/locale/sr/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/ga/"
%dir "//usr/share/locale/ga/LC_MESSAGES/"
"//usr/share/locale/ga/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/ro/"
%dir "//usr/share/locale/ro/LC_MESSAGES/"
"//usr/share/locale/ro/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/da/"
%dir "//usr/share/locale/da/LC_MESSAGES/"
"//usr/share/locale/da/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/fi/"
%dir "//usr/share/locale/fi/LC_MESSAGES/"
"//usr/share/locale/fi/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/fr/"
%dir "//usr/share/locale/fr/LC_MESSAGES/"
"//usr/share/locale/fr/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/hr/"
%dir "//usr/share/locale/hr/LC_MESSAGES/"
"//usr/share/locale/hr/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/af/"
%dir "//usr/share/locale/af/LC_MESSAGES/"
"//usr/share/locale/af/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/de/"
%dir "//usr/share/locale/de/LC_MESSAGES/"
"//usr/share/locale/de/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/pl/"
%dir "//usr/share/locale/pl/LC_MESSAGES/"
"//usr/share/locale/pl/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/wa/"
%dir "//usr/share/locale/wa/LC_MESSAGES/"
"//usr/share/locale/wa/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/hu/"
%dir "//usr/share/locale/hu/LC_MESSAGES/"
"//usr/share/locale/hu/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/sk/"
%dir "//usr/share/locale/sk/LC_MESSAGES/"
"//usr/share/locale/sk/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/tr/"
%dir "//usr/share/locale/tr/LC_MESSAGES/"
"//usr/share/locale/tr/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/sv/"
%dir "//usr/share/locale/sv/LC_MESSAGES/"
"//usr/share/locale/sv/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/uk/"
%dir "//usr/share/locale/uk/LC_MESSAGES/"
"//usr/share/locale/uk/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/sq/"
%dir "//usr/share/locale/sq/LC_MESSAGES/"
"//usr/share/locale/sq/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/bg/"
%dir "//usr/share/locale/bg/LC_MESSAGES/"
"//usr/share/locale/bg/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/el/"
%dir "//usr/share/locale/el/LC_MESSAGES/"
"//usr/share/locale/el/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/locale/sl/"
%dir "//usr/share/locale/sl/LC_MESSAGES/"
"//usr/share/locale/sl/LC_MESSAGES/libiconv.mo"
%dir "//usr/share/man/"
%dir "//usr/share/man/man3/"
"//usr/share/man/man3/iconv.3.gz"
"//usr/share/man/man3/iconv_close.3.gz"
"//usr/share/man/man3/iconv_open.3.gz"
"//usr/share/man/man3/iconvctl.3.gz"
"//usr/share/man/man3/iconv_open_into.3.gz"
%dir "//usr/share/man/man1/"
"//usr/share/man/man1/iconv.1.gz"
